name: Subscribio CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Gradle
      run: ./gradlew build
      
  tests:
    runs-on: macos-latest
    needs: [build]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Unit Tests
        uses: ReactiveCircus/android-emulator-runner@v2.11.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace
